version: "3.7"

services:

  watchtower:
    image: containrrr/watchtower:1.1.6
    container_name: 'watchtower'
    restart: unless-stopped
    command: --cleanup --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro

  pg-db:
    image: postgres:13.2
    container_name: pg-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - DB
      - DB_USER
      - DB_PASSWORD
    expose:
      - 5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    shm_size: '256m'

  pg-admin:
    image: dpage/pgadmin4:4.30
    container_name: pg-admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT=5001
    expose:
      - 5001
    volumes:
    - ./docker/pgadmin/data:/var/lib/pgadmin

  mongo-db:
    image: mongo:4.4.3
    container_name: mongo-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    expose:
      - 27017
    volumes:
    - ./docker/mongo/data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-db
    expose:
      - 8081
    depends_on:
      - mongo-db

  nginx-proxy:
    image: nginx:1.19.6
    container_name: nginx-proxy
    restart: unless-stopped
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ./docker/nginx/config/${NGINX_CONF_NAME}.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/cache:/var/cache/nginx
    ports:
      - 80:80
      - 443:443
      - 5001:5001
      - 5002:5002
    depends_on:
      - pg-admin
      - mongo-express
      - cog

  cog:
    image: seoulteam/castleofghosts:latest
    container_name: castleofghosts
    restart: unless-stopped
    environment:
      - DB_PG_URI
      - DB_MONGO_URI
    expose:
      - 3000
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - pg-db
      - mongo-db

